image: "node:16-slim"

stages:
 - publish

publish:
 stage: publish
 script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - yarn
    - yarn publish --new-version ${VERSION}
only:
  variables:
    ${RELEASE} == "yes"
