image: "node:16-slim"

variables:
  RELEASE: no

stages:
 - publish

publish:
 stage: publish
 script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - yarn
    - yarn publish --new-version ${VERSION}
 tags:
   - wavesenterprise
 only:
   variables:
     $RELEASE == "yes"
